# Note: Need to install pycurrents manually into this environment
name: gadcp
dependencies:
  - python
  - pip
  - mercurial
  - numpy
  - black
  - isort
  - flake8
  - pip:
    - -r requirements.txt
    - -e .
